name: personal_lisancer
description: Automatically create your lisance text for every file
version: 0.0.1
repository: "https://github.com/Abdusin/personal_lisancer"
author: Abdus Inanc <abdusinanc@gmail.com> 

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  tint: ^2.0.0
  yaml: ^3.1.0

dev_dependencies:
  test: ^1.16.7

